# Generated by Django 3.2.9 on 2021-11-21 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='Category',
            new_name='category',
        ),
    ]
